search_url = 'https://c.y.qq.com/soso/fcgi-bin/client_search_cp'
key_url = 'https://c.y.qq.com/base/fcgi-bin/fcg_music_express_mobile3.fcg'
play_url = 'http://bsy.stream.qqmusic.qq.com/'
play_url3 = 'http://tpt.music.qq.com/'
play_url2 = 'http://123.125.110.144/streamoc.music.tc.qq.com/'
lyric_url = 'https://c.y.qq.com/lyric/fcgi-bin/fcg_query_lyric.fcg'
album_img_url = 'https://y.gtimg.cn/music/photo_new/T002R300x300M000%s.jpg'
